### ISSUE TITLE
PListener priority: specify which to call first

### ISSUE THREAD

**Issue by flying-sheep** [reflux/refluxjs#199]
Hi, for reponsivity reasons I’d like to increase the priority for some listeners.

**Comment by spoike** [comment]
Do you have a story about a heavy processing on the client side which is making response times an issue?

**Comment by flying-sheep** [comment]
surely i have!

1. moving the mouse over some area triggers `Actions.selectArea`
2. A scatter chart with thousands of points, a bar chart with some 100 bars, and a network graph with a dozen edges listen to it each time the mouse is moved, updating the mentioned nodes
3. also a special crosshair is drawn on top of the hovered area ← i want this to happen first, without delay.

right now i have the `setState` to draw the component right next to the action triggering, but that’s obviously a hack.

**Comment by spoike** [comment]
I've been in a similar situation and noticed that spamming React with user inputs lead to sluggish renderer (which is true even in vanilla js even if you are effective with your DOM manipulation). A priority queue won't help you because:

1. The browser's renderer won't be able to keep up with the updates, and will be unresponsive until you stop moving the mouse
2. Javascript is single-threaded in browsers so starvation becomes a tangible issue

There are however some easy performance gains you can do:

1. Throttle/debounce your user inputs. In your case the mouse move event. This is the easiest gain in performance you can do. Modern browsers even come with `requestAnimationFrame`so you can [throttle with the renderer's actual framerate](http://spoike.ghost.io/user-input-framerate-throttling-in-the-browser/).

2. You can always force the browser to render with the GPU by using the translateZ hack moderately.
  ```css
.gpu {
      -webkit-transform : translateZ(0); 
      -o-transform : translateZ(0); 
      -moz-transform : translateZ(0); 
      transform : translateZ(0);   
      /* avoid flickering see:
         http://stackoverflow.com/questions/2946748/iphone-webkit-css-animations-cause-flicker/3461770#3461770 */
      -webkit-perspective: 1000;
      -webkit-backface-visibility: hidden;
}
  ```

3. Do note that you can change your mouse cursor with css instead.
  ```css
.customcursor {
        cursor: url("custom-cursor.gif"), auto;
}
  ```
Google Maps does this with custom cursors for dragging the map.

Also... always profile your code before making assumptions of performance. The true reason why performance is bad in your web application is usually counter-intuitive.
